### PR TITLE
fix: remove no-hydrate for custom.html element

### PR DESCRIPTION
**Pull request by thomas-wv**

### CODE REVIEW

**Comment by hta218** [comment]
This doesn't seem right, did you test with custom liquid?

**Comment by thomas-wv** [comment]
> This doesn't seem right, did you test with custom liquid?

image
image


yes, I try to remove `NoHydrate` comp and add some liquid code, everything works normally.

**Comment by paul-phan** [comment]
@thomas-wv make sure the extension is turned on correctly and no cached exist

**Comment by hta218** [comment]
Can you share the live view url & your storefront password?

**Comment by thomas-wv** [comment]
this is my record: https://www.loom.com/share/9d43760c0cb24287b8fea8b0835aa2d6

live view: https://duong-thomas-wv.myshopify.com/

pass: admin

**Comment by hta218** [comment]
Seem weird, I'll double-check on my side

**Comment by paul-phan** [comment]
@thomas-wv try to add elements that requires hydrate (js function to work) like Slider or Product Details

**Comment by thomas-wv** [comment]
> @thomas-wv try to add elements that requires hydrate (js function to work) like Slider or Product Details

I'm seeing a problem now, let me find other way to fix it

**Comment by paul-phan** [comment]
Seem like the problem is because of element not being refreshed when data change, try to find a way to fix it. Adding "key" for example.

**Pull request closed without merging**
